name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
  api_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Aqws12aqwsed
          POSTGRES_DB: crm-testing
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Newman
        run: npm install -g newman

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Load SQL dump
        env:
          PGPASSWORD: Aqws12aqwsed
        run: |
          # Wait for PostgreSQL to be ready
          until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done
          # Import your SQL dump
          psql -h localhost -p 5432 -U postgres -d crm-testing -f CmrDatabase.sql

      - name: Install dotnet project dependencies
        run: |
          cd crmsystem
          dotnet restore

      - name: Build
        run: |
          cd crmsystem
          dotnet build
        
      - name: Start Server
        run: cd crmsystem/server && nohup dotnet run &
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost;Port=5432;Database=crm-testing;User Id=postgres;Password=Aqws12aqwsed;"

      - name: Wait for server to start
        run: sleep 10

      - name: Run API-Tests
        run: newman run api-test/crmsystemet.postman_collection.json

  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests # Kör endast om api testerna går igenom
    steps:
      - name: Install wait-on
        run: npm install -g wait-on
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: |
          cd crmsystem
          dotnet restore
      - name: Build/Restore Playwright Project
        run: cd CrmTester.Tests && dotnet build
      - name: Ensure browsers are installed
        run: cd CrmTester.Tests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start frontend server
        run: |
          cd crmsystem/client
          nohup npm run dev > vite.log 2>&1 &
      - name: Start server
        run: cd server && nohup dotnet run &
      - name: Wait for frontend
        run: wait-on http://localhost:5173/login
      - name: Run GUI-tests
        run: cd CrmTester.Tests && dotnet test         