name: CI/CD Test

on:
  push:
    branches: ["main"]
jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Newman
        run: npm install -g newman

      - name: Restore dotnet dependencies
        run: dotnet restore
        working-directory: ./crmsystem

      - name: Build dotnet project
        run: dotnet build
        working-directory: ./crmsystem

      - name: Start Server
        run: nohup dotnet run &
        working-directory: ./crmsystem/server

      - name: Run API Tests
        run: newman run ./api-test/crmsystemet.postman_collection.json